:: Simple file to list Windows stored WiFi networks and passwords.
:: This was generated by Bing Copilot.
:: It is free to use by everyone.
::
:: Uses are: 
::     To show you the list of Wi-Fi networks on your laptop.
::     To make it clear how simple it is for someone to access your device
::        with a few simple lines of commands. 

@echo off
setlocal enabledelayedexpansion

REM Retrieve the list of saved Wi-Fi profiles
for /f "tokens=2 delims=:" %%a in ('netsh wlan show profile ^| findstr ":"') do (
    set "ssid=%%~a"
    call :getpwd "%%ssid:~1%%"
)

REM Function to retrieve the password for a given SSID
:getpwd
set "ssid=%*"
for /f "tokens=2 delims=:" %%i in ('netsh wlan show profile name^="%ssid%" key^=clear ^| findstr /C:"Key Content"') do (
    echo SSID: %ssid%   Password: %%i
)
